### ISSUE TITLE
Page does not stop loading

### ISSUE THREAD

**Issue by Silke-B** [jelovirt/pdf-generator#14]
Hello,
http://dita-generator.elovirta.com/ can not be used, it does not stop loading?
Tested on two PCs with FF, IE, Chrome.
Thank you in advance
Silke

**Comment by jelovirt** [comment]
The UI seems to be broken.

**Comment by hemantlucknow1** [comment]
The UI is not loading at all. Tried with different network and web browsers.

**Comment by imagineer64** [comment]
@jelovirt is fixing the UI something you plan to do or have you deprecated this utility? If you plan to fix it do think it will be a week a month a quarter?
Thanks

**Comment by jelovirt** [comment]
@imagineer64 @Silke-B finally got the app working. It was a simple thing, Heroku wasn't building the Javascript properly and I had to spend a couple of hours hammering the build. But now the app is finally up and working again.
