### ISSUE TITLE
topic2fo_shell_fop.xsl contains invalid link

### ISSUE THREAD

**Issue by xephon2** [jelovirt/pdf-generator#18]
When generating a 3.0 plugin for FOP, the `topic2fo_shell_fop.xsl` contains a link to a file, that does not exist anymore, at least in DITA-OT 3.2:

```xml
<xsl:import href="plugin:org.dita.pdf2.fop:cfg/fo/attrs/toc-attr_fop.xsl"/>
```

**Comment by takesson** [comment]
I saw this issue yesterday as well. Tested with DITA-OT 3.2.1 and 3.3.3.

After removing the above import I also got missing attribute sets until I added:
```
  <xsl:import href="plugin:org.dita.pdf2:cfg/fo/attrs/topic-attr.xsl" />
  <xsl:import href="plugin:org.dita.pdf2:cfg/fo/attrs/concept-attr.xsl" />
```

Not sure if this is the correct fix.

**Comment by jelovirt** [comment]
This will be handled in #21
