### ISSUE TITLE
Upload a zip plugin to modify its configuration

### ISSUE THREAD

**Issue by teclab-at** [jelovirt/pdf-generator#22]
Would be great if the tool allows uploading a previously generated pdf plugin

**Comment by jelovirt** [comment]
The easiest way to do this would be to generate a template file into the plug-in ZIP, e.g. `template.json`. You could then use that to get the generator initialized to equivalent UI state.

**Comment by jelovirt** [comment]
#29 implements the `template.json` functionality. Finishing the implementation will take some time but closing this issue at this stage already.
