### ISSUE TITLE
Rename odd/even to recto/verso

### ISSUE THREAD

**Issue by jelovirt** [jelovirt/pdf-generator#36]
Should `odd` and `even` page configuration keys be renamed to `recto` (right-hand, odd-numbered pages) and `verso` (left-hand, even-numbered pages), respectively? The new terms would be less common, but they would be more accurate. 

For example Asciidoctor PDF uses `recto` and `verso`

**Comment by jelovirt** [comment]
Ping @infotexture, what's your take?

**Comment by jelovirt** [comment]
Add support for both, but rewrite to one or the other during normalization stage.

**Comment by infotexture** [comment]
Sorry I missed this earlier, but I don't have a strong preference. 🤷 

The `odd`/`even` variants are probably more widely understood, but supporting `recto`/`verso` publishing jargon makes sense.

We can document them as alternatives if the final implementation supports both.
