### ISSUE TITLE
Entires wrongly repeated 3 times in simpletable

### ISSUE THREAD

**Issue by norweis** [jelovirt/pdf-generator#5]
In my sample, for a DITA
```xml
<simpletable relcolwidth="1* 5*" expanse="column" frame="none" keycol="1">
  <strow>
    <stentry>Name</stentry>
    <stentry>LongValue</stentry>
  </strow>
</simpletable>
````
the layout using the _simply generated plugin_ is always something like
```
Name       LongValue LongValue LongValue
Name
Name
```

Why are the entries repeated 3 times?

**Comment by jelovirt** [comment]
Which version of DITA-OT? Did you create the plugin with matching target version?

**Comment by norweis** [comment]
It was DITA-OT version 2.3, freshly fetched from http://www.dita-ot.org/download (now there is even 2.3.1, but it was 2.3.[0]).
In http://dita-generator.elovirta.com/#p1, DITA-OT version 2.3 was preselected, and I took that.  I installed the generated plugin with dita -install.
Should I try to install an older DITA-OT? Thanks for help.

**Comment by norweis** [comment]
Addendum: The normal pdf2 plugin of DITA-OT 2.3 displays the simpletables correctly.

**Comment by jelovirt** [comment]
Thanks for the details.

**Comment by norweis** [comment]
I made some experiments: It is definitely caused by the "Override shell" option on #p1. Without using it, it works correctly. When checking it, the content in all tables is tripled in each cell.
But I appreciate your great work very much.

**Comment by jelovirt** [comment]
The shell is probably generated incorrectly for 2.3.

**Comment by jelovirt** [comment]
Occurs on 2.2 too. The 2.3 output was missing a few imports in the shell, but that doesn't cause the issue.

**Comment by jelovirt** [comment]
If I remove all plugin generated imports from the shell, it still triples the simpletable content. Weird.

**Comment by jelovirt** [comment]
Seems to have something to do with flagging.

**Comment by jelovirt** [comment]
The root cause was a missing import from PDF2, the condition to check whether it's imported was wrong.
