### ISSUE TITLE
page header present despite selecting "empty"

### ISSUE THREAD

**Issue by ramendik** [jelovirt/pdf-generator#7]
I want a blank header and a blank footer. So I select "empty" for the header and do not select "drop folio".

Unfortunately, the page header still contains both the chapter title and the page number. (The page footer is blank).

I have attached the generated plugin.

[pdfmr1.zip](https://github.com/jelovirt/pdf-generator/files/407769/pdfmr1.zip)

**Comment by jelovirt** [comment]
The currently is no support in the UI to produce empty headers/footers. An improvement is planned.

**Comment by jelovirt** [comment]
Fixed in 0c686a1968799882fe0ebc90f0622ca38127e403
