### ISSUE TITLE
PDF `--theme`: Table font size not respected if cells contain elements

### ISSUE THREAD

**Issue by infotexture** [jelovirt/pdf-generator#79]
The `$style-table-font-size` key is applied to cells if plain text is used in table cells, but if `<entry>` elements contain other elements like `<p>`, `<ul>`, etc. the font size reverts to defaults, resulting in different font sizes for the elements in the cell.

![com-elovirta-pdf-nested-paras-in-table-cells](https://user-images.githubusercontent.com/129995/200161391-5d50b4b5-4d80-4d15-b02c-2415af46da3d.png)

**Comment by infotexture** [comment]
With the recent changes in d88b5e2, nested paragraphs & list items also seem to revert to the default body serif font, though tables are set to use sans:

```yaml
style:
  table:
    font-family: $pdf2-font-sans
```

**Comment by jelovirt** [comment]
Fixed by removing font properties from common.block
